//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CellularAutomataClient.RemoteServices {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CompilerErrors", Namespace="http://schemas.datacontract.org/2004/07/CellularAutomataLibrary")]
    [System.SerializableAttribute()]
    public partial class CompilerErrors : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsSuccessField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CellularAutomataClient.RemoteServices.CompilerMessage[] MessagesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsSuccess {
            get {
                return this.IsSuccessField;
            }
            set {
                if ((this.IsSuccessField.Equals(value) != true)) {
                    this.IsSuccessField = value;
                    this.RaisePropertyChanged("IsSuccess");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CellularAutomataClient.RemoteServices.CompilerMessage[] Messages {
            get {
                return this.MessagesField;
            }
            set {
                if ((object.ReferenceEquals(this.MessagesField, value) != true)) {
                    this.MessagesField = value;
                    this.RaisePropertyChanged("Messages");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CompilerMessage", Namespace="http://schemas.datacontract.org/2004/07/CellularAutomataLibrary")]
    [System.SerializableAttribute()]
    public partial class CompilerMessage : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorMessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int LineNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CellularAutomataClient.RemoteServices.Severity SeverityField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorMessage {
            get {
                return this.ErrorMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorMessageField, value) != true)) {
                    this.ErrorMessageField = value;
                    this.RaisePropertyChanged("ErrorMessage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int LineNumber {
            get {
                return this.LineNumberField;
            }
            set {
                if ((this.LineNumberField.Equals(value) != true)) {
                    this.LineNumberField = value;
                    this.RaisePropertyChanged("LineNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CellularAutomataClient.RemoteServices.Severity Severity {
            get {
                return this.SeverityField;
            }
            set {
                if ((this.SeverityField.Equals(value) != true)) {
                    this.SeverityField = value;
                    this.RaisePropertyChanged("Severity");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Severity", Namespace="http://schemas.datacontract.org/2004/07/CellularAutomataLibrary")]
    public enum Severity : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Warning = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Error = 1,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InvalidOperationFault", Namespace="http://schemas.datacontract.org/2004/07/CellularAutomataLibrary")]
    [System.SerializableAttribute()]
    public partial class InvalidOperationFault : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReasonField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Reason {
            get {
                return this.ReasonField;
            }
            set {
                if ((object.ReferenceEquals(this.ReasonField, value) != true)) {
                    this.ReasonField = value;
                    this.RaisePropertyChanged("Reason");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="RemoteServices.IRemoteCompilation")]
    public interface IRemoteCompilation {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRemoteCompilation/Compile", ReplyAction="http://tempuri.org/IRemoteCompilation/CompileResponse")]
        CellularAutomataClient.RemoteServices.CompilerErrors Compile(string code);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IRemoteCompilation/Compile", ReplyAction="http://tempuri.org/IRemoteCompilation/CompileResponse")]
        System.IAsyncResult BeginCompile(string code, System.AsyncCallback callback, object asyncState);
        
        CellularAutomataClient.RemoteServices.CompilerErrors EndCompile(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRemoteCompilation/Initialize", ReplyAction="http://tempuri.org/IRemoteCompilation/InitializeResponse")]
        void Initialize(byte[][] initialBoard);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IRemoteCompilation/Initialize", ReplyAction="http://tempuri.org/IRemoteCompilation/InitializeResponse")]
        System.IAsyncResult BeginInitialize(byte[][] initialBoard, System.AsyncCallback callback, object asyncState);
        
        void EndInitialize(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRemoteCompilation/Step", ReplyAction="http://tempuri.org/IRemoteCompilation/StepResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(CellularAutomataClient.RemoteServices.InvalidOperationFault), Action="http://tempuri.org/IRemoteCompilation/StepInvalidOperationFaultFault", Name="InvalidOperationFault", Namespace="http://schemas.datacontract.org/2004/07/CellularAutomataLibrary")]
        System.Collections.Generic.Dictionary<System.Tuple<int, int>, byte> Step();
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IRemoteCompilation/Step", ReplyAction="http://tempuri.org/IRemoteCompilation/StepResponse")]
        System.IAsyncResult BeginStep(System.AsyncCallback callback, object asyncState);
        
        System.Collections.Generic.Dictionary<System.Tuple<int, int>, byte> EndStep(System.IAsyncResult result);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IRemoteCompilationChannel : CellularAutomataClient.RemoteServices.IRemoteCompilation, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CompileCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public CompileCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public CellularAutomataClient.RemoteServices.CompilerErrors Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((CellularAutomataClient.RemoteServices.CompilerErrors)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class StepCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public StepCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public System.Collections.Generic.Dictionary<System.Tuple<int, int>, byte> Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((System.Collections.Generic.Dictionary<System.Tuple<int, int>, byte>)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RemoteCompilationClient : System.ServiceModel.ClientBase<CellularAutomataClient.RemoteServices.IRemoteCompilation>, CellularAutomataClient.RemoteServices.IRemoteCompilation {
        
        private BeginOperationDelegate onBeginCompileDelegate;
        
        private EndOperationDelegate onEndCompileDelegate;
        
        private System.Threading.SendOrPostCallback onCompileCompletedDelegate;
        
        private BeginOperationDelegate onBeginInitializeDelegate;
        
        private EndOperationDelegate onEndInitializeDelegate;
        
        private System.Threading.SendOrPostCallback onInitializeCompletedDelegate;
        
        private BeginOperationDelegate onBeginStepDelegate;
        
        private EndOperationDelegate onEndStepDelegate;
        
        private System.Threading.SendOrPostCallback onStepCompletedDelegate;
        
        public RemoteCompilationClient() {
        }
        
        public RemoteCompilationClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RemoteCompilationClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RemoteCompilationClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RemoteCompilationClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public event System.EventHandler<CompileCompletedEventArgs> CompileCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> InitializeCompleted;
        
        public event System.EventHandler<StepCompletedEventArgs> StepCompleted;
        
        public CellularAutomataClient.RemoteServices.CompilerErrors Compile(string code) {
            return base.Channel.Compile(code);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginCompile(string code, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginCompile(code, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public CellularAutomataClient.RemoteServices.CompilerErrors EndCompile(System.IAsyncResult result) {
            return base.Channel.EndCompile(result);
        }
        
        private System.IAsyncResult OnBeginCompile(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string code = ((string)(inValues[0]));
            return this.BeginCompile(code, callback, asyncState);
        }
        
        private object[] OnEndCompile(System.IAsyncResult result) {
            CellularAutomataClient.RemoteServices.CompilerErrors retVal = this.EndCompile(result);
            return new object[] {
                    retVal};
        }
        
        private void OnCompileCompleted(object state) {
            if ((this.CompileCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CompileCompleted(this, new CompileCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CompileAsync(string code) {
            this.CompileAsync(code, null);
        }
        
        public void CompileAsync(string code, object userState) {
            if ((this.onBeginCompileDelegate == null)) {
                this.onBeginCompileDelegate = new BeginOperationDelegate(this.OnBeginCompile);
            }
            if ((this.onEndCompileDelegate == null)) {
                this.onEndCompileDelegate = new EndOperationDelegate(this.OnEndCompile);
            }
            if ((this.onCompileCompletedDelegate == null)) {
                this.onCompileCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCompileCompleted);
            }
            base.InvokeAsync(this.onBeginCompileDelegate, new object[] {
                        code}, this.onEndCompileDelegate, this.onCompileCompletedDelegate, userState);
        }
        
        public void Initialize(byte[][] initialBoard) {
            base.Channel.Initialize(initialBoard);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginInitialize(byte[][] initialBoard, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginInitialize(initialBoard, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public void EndInitialize(System.IAsyncResult result) {
            base.Channel.EndInitialize(result);
        }
        
        private System.IAsyncResult OnBeginInitialize(object[] inValues, System.AsyncCallback callback, object asyncState) {
            byte[][] initialBoard = ((byte[][])(inValues[0]));
            return this.BeginInitialize(initialBoard, callback, asyncState);
        }
        
        private object[] OnEndInitialize(System.IAsyncResult result) {
            this.EndInitialize(result);
            return null;
        }
        
        private void OnInitializeCompleted(object state) {
            if ((this.InitializeCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.InitializeCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void InitializeAsync(byte[][] initialBoard) {
            this.InitializeAsync(initialBoard, null);
        }
        
        public void InitializeAsync(byte[][] initialBoard, object userState) {
            if ((this.onBeginInitializeDelegate == null)) {
                this.onBeginInitializeDelegate = new BeginOperationDelegate(this.OnBeginInitialize);
            }
            if ((this.onEndInitializeDelegate == null)) {
                this.onEndInitializeDelegate = new EndOperationDelegate(this.OnEndInitialize);
            }
            if ((this.onInitializeCompletedDelegate == null)) {
                this.onInitializeCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnInitializeCompleted);
            }
            base.InvokeAsync(this.onBeginInitializeDelegate, new object[] {
                        initialBoard}, this.onEndInitializeDelegate, this.onInitializeCompletedDelegate, userState);
        }
        
        public System.Collections.Generic.Dictionary<System.Tuple<int, int>, byte> Step() {
            return base.Channel.Step();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginStep(System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginStep(callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.Collections.Generic.Dictionary<System.Tuple<int, int>, byte> EndStep(System.IAsyncResult result) {
            return base.Channel.EndStep(result);
        }
        
        private System.IAsyncResult OnBeginStep(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return this.BeginStep(callback, asyncState);
        }
        
        private object[] OnEndStep(System.IAsyncResult result) {
            System.Collections.Generic.Dictionary<System.Tuple<int, int>, byte> retVal = this.EndStep(result);
            return new object[] {
                    retVal};
        }
        
        private void OnStepCompleted(object state) {
            if ((this.StepCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.StepCompleted(this, new StepCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void StepAsync() {
            this.StepAsync(null);
        }
        
        public void StepAsync(object userState) {
            if ((this.onBeginStepDelegate == null)) {
                this.onBeginStepDelegate = new BeginOperationDelegate(this.OnBeginStep);
            }
            if ((this.onEndStepDelegate == null)) {
                this.onEndStepDelegate = new EndOperationDelegate(this.OnEndStep);
            }
            if ((this.onStepCompletedDelegate == null)) {
                this.onStepCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnStepCompleted);
            }
            base.InvokeAsync(this.onBeginStepDelegate, null, this.onEndStepDelegate, this.onStepCompletedDelegate, userState);
        }
    }
}
